name: Kubesec and Kubelinter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Kubesec
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Kubesec scanner
        run: |
              wget https://github.com/controlplaneio/kubesec/releases/download/v2.14.2/kubesec_linux_amd64.tar.gz
              tar -xvf kubesec_linux_amd64.tar.gz
              mv kubesec /usr/local/bin/
              kubesec version

      - name: Generate Manifest file
        run: | 
           helm template demo-app > helm-template.yaml

      - name: Run kubesec scanner
        uses: controlplaneio/kubesec-action@43d0ddff5ffee89a6bb9f29b64cd865411137b14
        with:
          input: helm-template.yaml
          exit-code: "0"
          output: kubesec-results.sarif
        continue-on-error: true

      - name: Upload Kubesec scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: kubesec-results.sarif

      - name: Scan yamls
        id: kube-lint-scan
        uses: stackrox/kube-linter-action@v1
        with:
          directory: demo-app
          format: sarif
          output-file: kube-linter.sarif
        continue-on-error: true

      - name: Upload Kubesec scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: kube-linter.sarif
