name: Kubesec and Kubelinter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Kubesec
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Kubesec scanner
        run: |
              wget https://github.com/controlplaneio/kubesec/releases/download/v2.14.2/kubesec_linux_amd64.tar.gz
              tar -xvf kubesec_linux_amd64.tar.gz
              mv kubesec /usr/local/bin/
              kubesec version
              kubesec --help

      - name: Generate Manifest file
        run: helm template demo-app demo-app/ > manifests.yaml

      - name: Scan Manifest file
        run: kubesec scan manifests.yaml > kubesec-results.json
        continue-on-error: true

      - name: Upload Kubesec scan results as pipeline artifact
        uses: actions/upload-artifact@v4
        with:
          name: kubesec-results.json
          path: kubesec-results.json

      - name: Scan yamls
        id: kube-lint-scan
        uses: stackrox/kube-linter-action@v1.0.7
        with:
          directory: demo-app
          format: sarif
          output-file: kube-linter.sarif
        continue-on-error: true

      - name: Verify kube-linter-action succeeded
        shell: bash
        run: |
          echo "If this step fails, kube-linter found issues. Check the output of the scan step above."
          [[ "${{ steps.kube-linter-action-scan.outcome }}" == "success" ]]

      - name: Upload Kubesec scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: kube-linter.sarif
